# Generated by Django 4.2.7 on 2024-01-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('resim', models.FileField(upload_to='team_images')),
                ('brans', models.CharField(max_length=50)),
                ('dahili', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('ozgecmis', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
