# Generated by Django 4.2.7 on 2024-01-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=15)),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('mesaj', models.TextField(blank=True, null=True)),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointment.bolum')),
            ],
        ),
    ]
